### ISSUE TITLE
wrong variable name into toStr function

### ISSUE THREAD

**Issue by lucasmartinez** [sup3rb0wlz/polymer-nb-menu#1]
You must replace line 136:
   return JSON.stringify(value);

by 
   return JSON.stringify(input);

Regards

**Comment by NickBolles** [comment]
Hmm that's odd. I'll push the fix here soon. Thanks!

**Comment by NickBolles** [comment]
Ahhh looks like it was using the PolymerExpressions.prototype.toStr which is why it was still working.

New bower version available (1.0.12) with the fix. 

Were you actually experiencing an issue or did you just notice the typo?
